/**
 * Known English misspellings, and what they are misspellings *of*.
 *
 * WHY A LIST RATHER THAN A DICTIONARY
 *
 * The obvious approach is a spelling dictionary: flag any word it does not
 * know. That was tried, and it is wrong for this product. An English dictionary
 * does not know Turkish either, so it treats every Turkish word as a mistake and
 * offers the nearest English word — turning `askim` into `skim`. Tightening the
 * distance threshold does not save it, because short words in one language sit
 * one edit away from real words in another: `cok` → `cook`, `benim` → `benin`.
 *
 * There is no threshold that separates "a Turkish word" from "an English typo",
 * because the difference is not in the spelling. So the question is inverted:
 * rather than asking "is this word unknown?", which mistrusts every unfamiliar
 * word, this asks "is this a specific, known misspelling?", which mistrusts
 * nothing it has not been told about.
 *
 * The consequence is deliberate. It catches fewer typos than a dictionary
 * would, and in exchange it will never touch a word in another language, a pet
 * name, an invented spelling or a name. Given that the instruction was "if you
 * are not sure, do not even change the spelling", that is the right trade — and
 * the browser's own spell checker is still underlining everything else, in
 * whatever languages the reader has installed, right there in the editor.
 *
 * Adding to this list is safe and welcome: every entry is a word that is simply
 * never correct in English.
 */

export const COMMON_TYPOS: Readonly<Record<string, string>> = {
  // Transpositions and slips of the hand
  teh: "the",
  hte: "the",
  adn: "and",
  nad: "and",
  taht: "that",
  htat: "that",
  waht: "what",
  wnat: "want",
  jsut: "just",
  liek: "like",
  tihs: "this",
  thsi: "this",
  woudl: "would",
  coudl: "could",
  shoudl: "should",
  yuo: "you",
  yoru: "your",
  youre: "you're",
  ot: "to",
  fo: "of",
  cna: "can",
  ahve: "have",
  hvae: "have",
  taking: "taking",
  tommorow: "tomorrow",
  tommorrow: "tomorrow",
  tomorow: "tomorrow",
  yestarday: "yesterday",
  yesteday: "yesterday",

  // The classic vowel-order mistakes
  recieve: "receive",
  recieved: "received",
  recieving: "receiving",
  beleive: "believe",
  beleived: "believed",
  beleive_: "believe",
  acheive: "achieve",
  acheived: "achieved",
  peice: "piece",
  theif: "thief",
  wierd: "weird",
  freind: "friend",
  freinds: "friends",
  cheif: "chief",
  greif: "grief",
  releif: "relief",
  seige: "siege",
  thier: "their",
  wieght: "weight",
  hieght: "height",
  nieghbour: "neighbour",
  nieghbor: "neighbor",

  // Doubled or missing letters
  definately: "definitely",
  definatly: "definitely",
  defiantly_: "definitely",
  seperate: "separate",
  seperated: "separated",
  seperately: "separately",
  occured: "occurred",
  occuring: "occurring",
  occurance: "occurrence",
  begining: "beginning",
  beggining: "beginning",
  writting: "writing",
  writen: "written",
  comming: "coming",
  runing: "running",
  geting: "getting",
  puting: "putting",
  stoped: "stopped",
  planed: "planned",
  travelling_: "travelling",
  untill: "until",
  reccomend: "recommend",
  recomend: "recommend",
  reccommend: "recommend",
  accomodate: "accommodate",
  accomodation: "accommodation",
  neccessary: "necessary",
  necesary: "necessary",
  neccesary: "necessary",
  embarass: "embarrass",
  embarassed: "embarrassed",
  embarassing: "embarrassing",
  harrass: "harass",
  posession: "possession",
  posessed: "possessed",
  succesful: "successful",
  succesfully: "successfully",
  successfull: "successful",
  proffesional: "professional",
  profesional: "professional",
  comitted: "committed",
  commited: "committed",
  comittee: "committee",
  dissapoint: "disappoint",
  dissapointed: "disappointed",
  dissapear: "disappear",
  dissapeared: "disappeared",
  apparant: "apparent",
  arguement: "argument",
  enviroment: "environment",
  goverment: "government",
  independant: "independent",
  intresting: "interesting",
  interesing: "interesting",
  restaraunt: "restaurant",
  resturant: "restaurant",
  wich: "which",
  wih: "with",
  wiht: "with",
  witht: "with",
  becuase: "because",
  becasue: "because",
  becouse: "because",
  bacause: "because",
  alot: "a lot",
  atleast: "at least",
  infront: "in front",
  incase: "in case",
  aswell: "as well",
  eachother: "each other",

  // Everyday words people mistype in letters
  allways: "always",
  alway: "always",
  everytime: "every time",
  everyday_: "every day",
  somthing: "something",
  someting: "something",
  somethign: "something",
  nothign: "nothing",
  anythign: "anything",
  everythign: "everything",
  mabye: "maybe",
  mayb: "maybe",
  probaly: "probably",
  probally: "probably",
  probly: "probably",
  realy: "really",
  reallly: "really",
  verry: "very",
  finaly: "finally",
  usualy: "usually",
  actualy: "actually",
  basicly: "basically",
  completly: "completely",
  absolutly: "absolutely",
  immediatly: "immediately",
  suddenly_: "suddenly",
  eventualy: "eventually",
  espescially: "especially",
  especialy: "especially",
  exercise_: "exercise",
  excercise: "exercise",
  suprise: "surprise",
  suprised: "surprised",
  surpise: "surprise",
  rememeber: "remember",
  remeber: "remember",
  rember: "remember",
  forgt: "forgot",
  thougth: "thought",
  thoght: "thought",
  brnig: "bring",
  moring: "morning",
  mornign: "morning",
  eveing: "evening",
  nigth: "night",
  tonigth: "tonight",
  tonite: "tonight",
  todya: "today",
  toady_: "today",
  wekend: "weekend",
  weekedn: "weekend",
  familiy: "family",
  famly: "family",
  peopel: "people",
  peolpe: "people",
  becoem: "become",
  wanna_: "want to",
  gonna_: "going to",

  // Feelings, which is most of what a love letter is made of
  lovley: "lovely",
  luahg: "laugh",
  laught: "laughed",
  smilling: "smiling",
  happyness: "happiness",
  happines: "happiness",
  saddnes: "sadness",
  lonly: "lonely",
  lonley: "lonely",
  beatiful: "beautiful",
  beautifull: "beautiful",
  beutiful: "beautiful",
  gorgous: "gorgeous",
  gorgeus: "gorgeous",
  greatful: "grateful",
  gratefull: "grateful",
  wonderfull: "wonderful",
  woderful: "wonderful",
  amazign: "amazing",
  amasing: "amazing",
  favourtie: "favourite",
  favorite_: "favourite",
  miss_: "miss",
  misss: "miss",
  kisss: "kiss",
  hugg: "hug",

  // Contractions people drop the apostrophe from
  dont: "don't",
  doesnt: "doesn't",
  didnt: "didn't",
  cant: "can't",
  couldnt: "couldn't",
  wouldnt: "wouldn't",
  shouldnt: "shouldn't",
  isnt: "isn't",
  arent: "aren't",
  wasnt: "wasn't",
  werent: "weren't",
  havent: "haven't",
  hasnt: "hasn't",
  hadnt: "hadn't",
  wont: "won't",
  im_: "I'm",
  ive: "I've",
  ill_: "I'll",
  id_: "I'd",
  thats: "that's",
  its_: "it's",
  lets_: "let's",
  theres: "there's",
  wheres: "where's",
  whats: "what's",
  hes_: "he's",
  shes: "she's",
  weve: "we've",
  theyve: "they've",
  theyre: "they're",
  wouldve: "would've",
  couldve: "could've",
  shouldve: "should've",
};

/**
 * Entries above ending in `_` are placeholders kept out of the active map:
 * either the "misspelling" is a real word in some contexts (`its`, `lets`,
 * `defiantly`) or the correction is a matter of taste (`favorite`). Correcting
 * those needs to understand the sentence, which this deliberately does not.
 */
const AMBIGUOUS = /_$/;

export const TYPO_CORRECTIONS: ReadonlyMap<string, string> = new Map(
  Object.entries(COMMON_TYPOS).filter(([misspelling]) => !AMBIGUOUS.test(misspelling)),
);

/** The correction for a word, or null if it is not a known misspelling. */
export function correctionFor(word: string): string | null {
  return TYPO_CORRECTIONS.get(word.toLowerCase()) ?? null;
}
